name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build and run tests with Maven
      - name: Build and run tests
        run: mvn clean verify

      # Generate code coverage report
      - name: Generate JaCoCo report
        run: mvn jacoco:report

      # Upload code coverage report as artifact
      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco
